/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BlockChain;

/**
 *
 * @author raul4
 */
public class formViajes extends javax.swing.JFrame {

    /**
     * Creates new form formViajes
     */
    public formViajes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tDestino = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cVehiculos = new javax.swing.JComboBox<>();
        cClientes = new javax.swing.JComboBox<>();
        cConductores = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Crear Viajes");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(207, 11, 102, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Origen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 70, 52, 22);

        tOrigen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(tOrigen);
        tOrigen.setBounds(170, 70, 110, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Vehiculo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 270, 70, 22);

        tDestino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tDestino);
        tDestino.setBounds(170, 120, 110, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Crear Viaje");
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 240, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Destino");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 59, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cliente");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 170, 53, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Conductor");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 220, 90, 22);

        cVehiculos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cVehiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cVehiculos);
        cVehiculos.setBounds(170, 270, 110, 28);

        cClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cClientes);
        cClientes.setBounds(170, 170, 110, 28);

        cConductores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cConductores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cConductores);
        cConductores.setBounds(170, 220, 110, 28);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Ver Rutas");
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 100, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tOrigenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cClientes;
    private javax.swing.JComboBox<String> cConductores;
    private javax.swing.JComboBox<String> cVehiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tDestino;
    private javax.swing.JTextField tOrigen;
    // End of variables declaration//GEN-END:variables
}
